site_name: android
nav: 
    - index.md
    - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³:
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/index.md
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/1.èƒŒæ™¯ç›¸å…³ä¸ç³»ç»Ÿæ¶æ„åˆ†æ.md
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/2.å¼€å‘ç¯å¢ƒæ­å»º.md
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/3.SDK æ›´æ–°ä¸äº†é—®é¢˜è§£å†³.md
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/4.Genymotionæ¨¡æ‹Ÿå™¨å®‰è£…ä½¿ç”¨.md
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/5.Gitç‰ˆæœ¬ç®¡ç†.md
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/6..9å›¾ç‰‡åˆ¶ä½œ.md
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/7.ç•Œé¢åŸå‹è®¾è®¡.md
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/8.å·¥ç¨‹ç›¸å…³è§£æ.md
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/9.Androidç¨‹åºç­¾åæ‰“åŒ….md
        - 1.ç¯å¢ƒæ­å»ºï¼Œå¼€å‘ç›¸å…³/10.åç¼–è¯‘apkè·å¾—ä»£ç ä¸èµ„æº.md
    - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶:
        - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶/index.md
        - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶/1.Viewä¸ViewGroupæ¦‚å¿µ.md
        - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶/2.å¸ƒå±€.md
        - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶/3.å¸¸ç”¨åŸºæœ¬æ§ä»¶.md
        - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶/4.æ—¥æœŸç±»æ§ä»¶.md
        - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶/5.Adapteræ§ä»¶.md
        - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶/6.æç¤ºç±»æ§ä»¶.md
        - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶/7.èœå•ç±»æ§ä»¶.md
        - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶/8.å…¶ä»–æ§ä»¶.md
        - 2.å¸¸ç”¨UIæ§ä»¶ä¸äº‹ä»¶å¤„ç†æœºåˆ¶/9.äº‹ä»¶å¤„ç†æœºåˆ¶.md
    - 3.Androidå››å¤§ç»„ä»¶å’ŒIntentç»„ä»¶:
        - 3.Androidå››å¤§ç»„ä»¶å’ŒIntentç»„ä»¶/index.md
        - 3.Androidå››å¤§ç»„ä»¶å’ŒIntentç»„ä»¶/1.Actviity(æ´»åŠ¨).md
        - 3.Androidå››å¤§ç»„ä»¶å’ŒIntentç»„ä»¶/2.Service(æœåŠ¡).md
        - 3.Androidå››å¤§ç»„ä»¶å’ŒIntentç»„ä»¶/3.BroadcastReceiver(å¹¿æ’­).md
        - 3.Androidå››å¤§ç»„ä»¶å’ŒIntentç»„ä»¶/4.ContentProvider(å†…å®¹æä¾›è€…).md
        - 3.Androidå››å¤§ç»„ä»¶å’ŒIntentç»„ä»¶/5.Intent(æ„å›¾).md
    - 4.Fragment:
        - 4.Fragment/index.md
        - 4.Fragment/FragmentåŸºæœ¬æ¦‚è¿°.md
    - 5.æ•°æ®å­˜å‚¨:
        - 5.æ•°æ®å­˜å‚¨/index.md
        - 5.æ•°æ®å­˜å‚¨/1.æ–‡ä»¶å­˜å‚¨è¯»å†™.md
        - 5.æ•°æ®å­˜å‚¨/2.SharedPreference.md
        - 5.æ•°æ®å­˜å‚¨/3.SQLite.md
    - 6.ç½‘ç»œç¼–ç¨‹:
        - 6.ç½‘ç»œç¼–ç¨‹/index.md
        - 6.ç½‘ç»œç¼–ç¨‹/1.HTTPè¯¦è§£.md
        - 6.ç½‘ç»œç¼–ç¨‹/2.XMLæ•°æ®è§£æ.md
        - 6.ç½‘ç»œç¼–ç¨‹/3.Jsonæ•°æ®è§£æ.md
        - 6.ç½‘ç»œç¼–ç¨‹/4.Androidæ–‡ä»¶ä¸Šä¼ ä¸‹è½½.md
        - 6.ç½‘ç»œç¼–ç¨‹/5.è°ƒç”¨WebService.md
        - 6.ç½‘ç»œç¼–ç¨‹/6.WebView.md
        - 6.ç½‘ç»œç¼–ç¨‹/7.Socket.md
    - 7.ç»˜å›¾ä¸åŠ¨ç”»:
        - 7.ç»˜å›¾ä¸åŠ¨ç”»/index.md
        - 7.ç»˜å›¾ä¸åŠ¨ç”»/1.Drawable.md
        - 7.ç»˜å›¾ä¸åŠ¨ç”»/2.Bitmap.md
        - 7.ç»˜å›¾ä¸åŠ¨ç”»/3.ç»˜å›¾ç›¸å…³API.md
        - 7.ç»˜å›¾ä¸åŠ¨ç”»/4.åŠ¨ç”».md
    - 8.å¤šåª’ä½“å¼€å‘:
        - 8.å¤šåª’ä½“å¼€å‘/index.md
        - 8.å¤šåª’ä½“å¼€å‘/1.SoundPoolæ’­æ”¾éŸ³æ•ˆ.md
        - 8.å¤šåª’ä½“å¼€å‘/2.MediaPlayeræ’­æ”¾éŸ³è§†é¢‘.md
        - 8.å¤šåª’ä½“å¼€å‘/3.Caremeæ‹ç…§.md
        - 8.å¤šåª’ä½“å¼€å‘/4.MediaRecordå½•éŸ³.md
    - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½:
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/index.md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/1.TelephonManager(ç”µè¯ç®¡ç†å™¨).md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/2.SmsManager(çŸ­ä¿¡ç®¡ç†).md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/3.AudioManager(éŸ³é¢‘ç®¡ç†å™¨.md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/4.Vibrator(éœ‡åŠ¨å™¨).md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/5.AlarmManager(é—¹é’ŸæœåŠ¡).md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/6.PowerManager(ç”µæºæœåŠ¡).md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/7.WindowManager(çª—å£ç®¡ç†æœåŠ¡).md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/8.LayoutInflater(å¸ƒå±€ç®¡ç†å™¨).md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/9.WallpaperManager(å£çº¸ç®¡ç†å™¨).md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/10.ä¼ æ„Ÿå™¨.md
        - 9.ç³»ç»ŸAPIï¼Œåœ°å›¾å®šä½/11.GPS.md
    - 10.é¡¹ç›®å®æˆ˜:
        - 10.é¡¹ç›®å®æˆ˜/index.md
        - 10.é¡¹ç›®å®æˆ˜/DrySisterçœ‹å¦¹å­åº”ç”¨å®æˆ˜.md
        
extra_css:
    - res/extra.css
extra_javascript:
    - res/extra.js

    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2022 - 2023 travis

# repo_url: @
# repo_name: @

theme:
    name: material
    # custom_dir: overrides

    palette:
        - media: "(prefers-color-scheme)"
          primary: red
          accent: red
          toggle:
            icon: material/brightness-auto
            name: åˆ‡æ¢åˆ°æš—æ¨¡å¼
        - media: "(prefers-color-scheme: light)"
          primary: green
          accent: green
          scheme: default 
          toggle:
            icon: material/brightness-7
            name: åˆ‡æ¢åˆ°é»˜è®¤æ¨¡å¼
        - media: "(prefers-color-scheme: dark)"
          primary: blue
          accent: blue
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: åˆ‡æ¢åˆ°äº®æ¨¡å¼

    font:
        text: Roboto
        code: Roboto Mono

    language: zh
    direction: ltr

    logo: https://pic.peo.pw/a/2023/01/12/63bfb934b1b06.png
    favicon: https://pic.peo.pw/a/2023/01/12/63bfb934b1b06.png
    icon:
        logo: octicons/heart-fill-24

        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye


        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left




    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        # - navigation.expand
        - navigation.prune
        - navigation.indexes
        - toc.follow
        # - toc.integrate
        - navigation.top

        - search.suggest
        - search.highlight
        - search.share

        - header.autohide

        - navigation.footer

        - content.action.edit
        - content.action.view

        - content.code.copy
        - content.code.annotate

        - content.tooltips


extra:
    alternate:
        - name: English
          link: /en/ 
          lang: en
        - name: ä¸­æ–‡
          link: /zh/
          lang: zh

    homepage: /

    #consent:
    #    title: cookie
    #    description:    >-
    #        sdd
    #    cookies:
    #        analytics:
    #            github


    social:
        - icon: fontawesome/brands/github
          link: é“¾æ¥urlåœ°å€
          name: æ ‡è¯†å
        - icon: fontawesome/brands/docker
          link: é“¾æ¥urlåœ°å€
          name: æ ‡è¯†å
    generator: false


plugins:
    - search:
        lang:
            - en
            - ja
        # '[\s\-,:!=\[\]]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
        separator: '[\s\-\.`]+'
        jieba_dict: res/dict.txt
        jieba_dict_user: res/user_dict.txt
    # - typeset

    - glightbox

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

    - attr_list
    - md_in_html
    - pymdownx.superfences

    - attr_list

    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    #- pymdownx.tabbed:
    #    slugify: !!python/object/apply:pymdownx.slugs.slugify
    #        kwds:
    #            case: lower

    # - content.tabs.link


    - tables
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes

    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg


    - attr_list
    - md_in_html

    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

    - pymdownx.arithmatex:
        generic: true

    - abbr
    - attr_list
    - pymdownx.snippets
    - pymdownx.snippets:
        auto_append:
            - includes/abbr.md
    
    - toc:
        permalink: ğŸ‘ˆğŸ‘ˆğŸ‘ˆ
        title: ç›®å½•
        permalink_title: Anchor link to this section for reference
        
        slugify: !!python/object/apply:pymdownx.slugs.slugify
            kwds:
              case: lower
        toc_depth: 3

